[package]
name = "rustyswords"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.78.2"
screenshots = "0.5.3"

[dependencies.winapi]
version = "0.3.9"
features = ["winuser"]
